package assets

var Json []byte = []byte(`{
	"prefixes": [
	  "aero",
	  "ana",
	  "ante",
	  "anti",
	  "auto",
	  "bi",
	  "bulbo",
	  "capillo",
	  "circum",
	  "contra",
	  "crypto",
	  "de",
	  "dis",
	  "epi",
	  "ex",
	  "exo",
	  "extra",
	  "fore",
	  "hepta",
	  "hetero",
	  "homo",
	  "hyper",
	  "infra",
	  "inter",
	  "intra",
	  "macro",
	  "mega",
	  "meta",
	  "micro",
	  "mid",
	  "mini",
	  "mis",
	  "mono",
	  "morpho",
	  "morvo",
	  "multi",
	  "neo",
	  "non",
	  "nucleo",
	  "octo",
	  "omni",
	  "over",
	  "para",
	  "penta",
	  "poly",
	  "post",
	  "pre",
	  "proto",
	  "pseudo",
	  "psycho",
	  "pyro",
	  "quadri",
	  "retro",
	  "semi",
	  "servo",
	  "spiro",
	  "sub",
	  "super",
	  "therm",
	  "thermo",
	  "theta",
	  "trans",
	  "tri",
	  "turbo",
	  "under",
	  "uni"
	],
	"adjectives": [
	  "a la carte",
	  "a la king",
	  "a la mode",
	  "acerbic",
	  "acidic",
	  "acrid",
	  "aftertaste",
	  "aged",
	  "airy",
	  "al dente",
	  "alcoholic",
	  "almond flavored",
	  "amazing",
	  "ambrosia",
	  "ambrosial",
	  "ample",
	  "appealing",
	  "appetizing",
	  "aroma",
	  "aromatic",
	  "astringent",
	  "au fromage",
	  "au gratin",
	  "au jus",
	  "baked",
	  "balsamic",
	  "barbecue",
	  "basted",
	  "bathed in",
	  "battered",
	  "beautiful",
	  "bite-size",
	  "biting",
	  "bitter",
	  "bittersweet",
	  "blackened",
	  "blah",
	  "blanched",
	  "bland",
	  "blended",
	  "boiled",
	  "bold",
	  "bolognese",
	  "boneless",
	  "brackish",
	  "braised",
	  "breaded",
	  "brewed",
	  "briny",
	  "brittle",
	  "broiled",
	  "browned",
	  "bubbly",
	  "burning",
	  "burnt",
	  "bursting",
	  "butterflied",
	  "buttery",
	  "béarnaise",
	  "cacciatore",
	  "cakey",
	  "candied",
	  "candy-coated",
	  "canned",
	  "caramelized",
	  "caustic",
	  "chalky",
	  "charbroiled",
	  "charcuterie",
	  "charred",
	  "cheesy",
	  "chewy",
	  "chili",
	  "chilled",
	  "chipotle",
	  "chocolaty",
	  "choice",
	  "chopped",
	  "chowder",
	  "chunky",
	  "clarified",
	  "classic",
	  "classical",
	  "classy",
	  "cold",
	  "colorful",
	  "comfort food",
	  "comforting",
	  "condensed",
	  "condiment",
	  "cool",
	  "copious",
	  "course",
	  "crafted",
	  "creamed",
	  "creamery",
	  "creamy",
	  "creole",
	  "crisp",
	  "crispy",
	  "crumbly",
	  "crunchy",
	  "crusty",
	  "crystalized",
	  "cuisine",
	  "curd",
	  "curdled",
	  "cured",
	  "curried",
	  "dainty",
	  "dash",
	  "dazzling",
	  "decadent",
	  "deglaze",
	  "dehyrated",
	  "delectable",
	  "delicate",
	  "delicious",
	  "delightful",
	  "deluxe",
	  "devein",
	  "deviled",
	  "diced",
	  "dietary",
	  "diluted",
	  "dipping",
	  "disagreeable",
	  "disgusting",
	  "distasteful",
	  "distinctive",
	  "divine",
	  "doughy",
	  "dredged",
	  "drenched",
	  "dressed",
	  "dried out",
	  "dripping",
	  "drizzled",
	  "dry",
	  "dry-roasted",
	  "dulcified",
	  "dull",
	  "dusted",
	  "earthy",
	  "eatable",
	  "edible",
	  "eggy",
	  "elastic",
	  "elegant",
	  "encrusted",
	  "enjoyable",
	  "enticing",
	  "entrée",
	  "escalloped",
	  "etouffee",
	  "evaporated",
	  "excellent",
	  "exquisite",
	  "extraordinary",
	  "fantastic",
	  "fatty",
	  "feathery",
	  "fermented",
	  "fibrous",
	  "fiery",
	  "filling",
	  "fine",
	  "finger licking",
	  "fishy",
	  "fizzy",
	  "flakey",
	  "flambé",
	  "flaming",
	  "flat",
	  "flavorful",
	  "flavorless",
	  "flavorsome",
	  "fleshy",
	  "florentine",
	  "floury",
	  "fluffy",
	  "foie gras",
	  "folded",
	  "foul",
	  "fra diablo",
	  "fragrant",
	  "freeze dried",
	  "fresh",
	  "fricasseed",
	  "fried",
	  "from scratch",
	  "frosted",
	  "frosty",
	  "frozen",
	  "fruity",
	  "fudgy",
	  "full",
	  "full-bodied",
	  "full-flavored",
	  "gamy",
	  "garden",
	  "garden-fresh",
	  "garlicky",
	  "gastric",
	  "gelatinous",
	  "generous",
	  "gingery",
	  "glazed",
	  "gloppy",
	  "glossy",
	  "gluteny",
	  "golden",
	  "good",
	  "gooey",
	  "gorgeous",
	  "gourmet",
	  "grainy",
	  "granulated",
	  "grated",
	  "gratifying",
	  "greasy",
	  "griddled",
	  "grilled",
	  "gritty",
	  "gross",
	  "guiltless",
	  "hardboiled",
	  "harsh",
	  "heady",
	  "healthy",
	  "heaping",
	  "heart-healthy",
	  "hearty",
	  "heat",
	  "heavenly",
	  "heavy",
	  "herbaceous",
	  "hint",
	  "homemade",
	  "homestyle",
	  "homogenized",
	  "honeyed",
	  "hors d'oeuvre",
	  "hot",
	  "hot sauce",
	  "ice-cold",
	  "iced",
	  "icy",
	  "indulgent",
	  "infused",
	  "intense",
	  "intriguing",
	  "inviting",
	  "juicy",
	  "julienne",
	  "jumbo",
	  "kick",
	  "kosher",
	  "laced",
	  "laden",
	  "laiche",
	  "lavish",
	  "layered",
	  "lean",
	  "leathery",
	  "lemony",
	  "light",
	  "limp",
	  "lip-smacking",
	  "liquid",
	  "loaded",
	  "low-fat",
	  "lumpy",
	  "luscious",
	  "lush",
	  "lusty",
	  "lyonnaise",
	  "malodorous",
	  "marinate",
	  "marvelous",
	  "mashed",
	  "mealy",
	  "meaty",
	  "medium",
	  "mellow",
	  "melt-in-your-mouth",
	  "melting",
	  "messy",
	  "microwave",
	  "mild",
	  "milky",
	  "minced",
	  "minty",
	  "mixed",
	  "moist",
	  "moldy",
	  "mouth-watering",
	  "muddy",
	  "mushy",
	  "nasty",
	  "natural",
	  "nauseating",
	  "nectarous",
	  "nosey",
	  "nostalgic",
	  "nourishing",
	  "noxious",
	  "nuked",
	  "nutriment",
	  "nutritious",
	  "nutty",
	  "odoriferous",
	  "odorless",
	  "oily",
	  "oniony",
	  "oozing",
	  "organic",
	  "overpowering",
	  "overripe",
	  "palatable",
	  "palate-pleasing",
	  "pan-fried",
	  "paprika",
	  "parboiled",
	  "parched",
	  "pasteurized",
	  "pasty",
	  "peck",
	  "penetrating",
	  "peppered",
	  "peppery",
	  "perfumed",
	  "perishable",
	  "piccata",
	  "pickled",
	  "piping",
	  "piquant",
	  "plain",
	  "pleasant",
	  "pleasing",
	  "plump",
	  "poached",
	  "popular",
	  "potent",
	  "pouched",
	  "powdered",
	  "powdery",
	  "preserved",
	  "puffy",
	  "pulpy",
	  "pulverized",
	  "pungent",
	  "puréed",
	  "pâté",
	  "ragout",
	  "rancid",
	  "rank",
	  "rare",
	  "raw",
	  "redolent",
	  "reduced",
	  "reeking",
	  "refreshing",
	  "relish",
	  "retro",
	  "rib sticking",
	  "rich",
	  "ripe",
	  "roasted",
	  "robust",
	  "rotten",
	  "rubbery",
	  "ruined",
	  "runny",
	  "saccharine",
	  "saline",
	  "salted",
	  "salty",
	  "sapid",
	  "saporous",
	  "satiny",
	  "satisfying",
	  "saturated",
	  "sautéed",
	  "savory",
	  "scalded",
	  "scented",
	  "scorched",
	  "scrambled",
	  "scrumptious",
	  "seared",
	  "seasonal",
	  "seasoned",
	  "sharp",
	  "shredded",
	  "signature",
	  "silky",
	  "simmering",
	  "simple",
	  "sizzling",
	  "skillfully",
	  "skimmed",
	  "skunky",
	  "slathered",
	  "sliced",
	  "slimey",
	  "slivered",
	  "smelly",
	  "smoked",
	  "smokey",
	  "smooth",
	  "smothered",
	  "snappy",
	  "soaked",
	  "sodden",
	  "soft",
	  "soft-boiled",
	  "soggy",
	  "soothing",
	  "sordid",
	  "soufflé",
	  "soupy",
	  "sour",
	  "sparkling",
	  "special",
	  "spiced",
	  "spicy",
	  "spiraled",
	  "spirited",
	  "spoiled",
	  "spongy",
	  "spread",
	  "sprinkled",
	  "stale",
	  "starchy",
	  "steamy",
	  "stewed",
	  "sticky",
	  "stiff",
	  "stinging",
	  "stinky",
	  "stringy",
	  "strong",
	  "stuffed",
	  "subdued",
	  "subtle",
	  "succulent",
	  "sugar free",
	  "sugar-coated",
	  "sugared",
	  "sugary",
	  "sunnyside up",
	  "superb",
	  "sweet",
	  "sweet and sour",
	  "sweetened",
	  "syrupy"
	],
	"ingredients": [
	  "sprout",
	  "lemon",
	  "brazil nuts",
	  "quiche",
	  "spearmint",
	  "lemon",
	  "cocoa powder",
	  "rice milk",
	  "Kahlua",
	  "tart",
	  "parsnip",
	  "brussels sprout",
	  "seaweed",
	  "wafer",
	  "gravy",
	  "sauerkraut",
	  "cinnamon",
	  "romaine lettuce",
	  "white bean",
	  "lemon juice",
	  "peanut butter",
	  "baking powder",
	  "kale",
	  "wheat",
	  "tofu",
	  "marionberry",
	  "salad",
	  "squash",
	  "chicory",
	  "sour cream",
	  "apple",
	  "wild rice",
	  "coconut cream",
	  "portabello mushroom",
	  "aspic",
	  "wasabi",
	  "brown sugar",
	  "apple pie spice",
	  "rose water",
	  "garlic powder",
	  "cumin",
	  "pretzel",
	  "maple syrup",
	  "chocolate",
	  "dragonfruit",
	  "hoisin sauce",
	  "kidney bean",
	  "kiwi fruit",
	  "pea beans",
	  "soy ice cream",
	  "prune",
	  "sunflower seed",
	  "cornflake",
	  "unsweetened chocolate",
	  "fennel seed",
	  "cornmeal",
	  "eggplant",
	  "bean sauce",
	  "radish",
	  "tamale",
	  "caramel",
	  "wine vinegar",
	  "summer squash",
	  "popcorn",
	  "artificial sweetener",
	  "mushroom",
	  "cremini mushrooms",
	  "oats",
	  "chickpeas",
	  "anise",
	  "barbecue",
	  "rum",
	  "honeydew melon",
	  "red beans",
	  "hazelnut",
	  "saffron",
	  "green bean",
	  "red cabbage",
	  "sherbet",
	  "thyme",
	  "sorbet",
	  "brown rice",
	  "peaches",
	  "toffee",
	  "apple butter",
	  "zucchini",
	  "chives",
	  "baking soda",
	  "cabbage",
	  "almond milk",
	  "quinoa",
	  "icing",
	  "guacamole",
	  "oregano",
	  "sweet chilli sauce",
	  "peach",
	  "pink beans",
	  "remoulade",
	  "corn flour",
	  "syrup",
	  "celery seeds",
	  "allspice",
	  "coconut",
	  "soy beans",
	  "snap pea",
	  "sweet potato",
	  "lima bean",
	  "currant",
	  "watermelon",
	  "vegemite",
	  "corn syrup",
	  "pasta",
	  "grape",
	  "onion",
	  "bagel",
	  "dried leek",
	  "jelly",
	  "tuber",
	  "cooking wine",
	  "pomegranate",
	  "raw sugar",
	  "pumpernickel",
	  "water",
	  "coconut oil",
	  "papaya",
	  "salsa",
	  "apricot",
	  "pancetta",
	  "maize",
	  "oatmeal",
	  "breadcrumb",
	  "Marsala",
	  "plum",
	  "pita bread",
	  "ginger ale",
	  "molasses",
	  "ravioli",
	  "hummus",
	  "huckleberry",
	  "cilantro",
	  "capers",
	  "citrus",
	  "frosting",
	  "salt",
	  "parsley",
	  "zinfandel wine",
	  "brandy",
	  "beet",
	  "tomato paste",
	  "rye",
	  "peanut",
	  "legume",
	  "beancurd",
	  "jackfruit",
	  "waffle",
	  "cauliflower",
	  "navy beans",
	  "tomatillo",
	  "mint",
	  "pea",
	  "carrot",
	  "orange peels",
	  "bok choy",
	  "cider vinegar",
	  "split pea",
	  "cream of tartar",
	  "tomato puree",
	  "mandarin",
	  "green onion",
	  "habanero chillies",
	  "maraschino cherry",
	  "almond",
	  "arugula",
	  "tangerine",
	  "jalapeno",
	  "spud",
	  "baguette",
	  "rosemary",
	  "potato chip",
	  "durian",
	  "licorice",
	  "strudel",
	  "tomato",
	  "brunoise",
	  "mascarpone",
	  "jelly bean",
	  "barley",
	  "chilli sauce",
	  "nectar",
	  "pumpkin",
	  "buckwheat",
	  "celery",
	  "pineapple",
	  "torte",
	  "pear",
	  "snow pea",
	  "pepper",
	  "bay leaf",
	  "tonic water",
	  "boysenberry",
	  "tortilla",
	  "kumquat",
	  "dandelion",
	  "heavy cream",
	  "chilli powder",
	  "noodle",
	  "Worcestershire sauce",
	  "cornstarch",
	  "date",
	  "blackberry",
	  "vinegar",
	  "provolone",
	  "red chile powder",
	  "hash brown",
	  "taco",
	  "sage",
	  "sesame seed",
	  "soy milk",
	  "lemonade",
	  "margarine",
	  "fig",
	  "broccoli",
	  "raisin",
	  "bean sprout",
	  "applesauce",
	  "pecan",
	  "chestnut",
	  "horseradish",
	  "bean thread",
	  "black-eyed pea",
	  "rice wine",
	  "water chestnut",
	  "tartar sauce",
	  "relish",
	  "balsamic vinegar",
	  "mustard seeds",
	  "ginger",
	  "alfalfa sprout",
	  "mayonnaise",
	  "rice",
	  "asparagus",
	  "bean",
	  "panko bread crumbs",
	  "rice paper",
	  "succotash",
	  "curry powder",
	  "banana",
	  "barley sugar",
	  "artichoke",
	  "olive",
	  "almond butter",
	  "lemon peel",
	  "curry leaves",
	  "chip",
	  "coconut ice cream",
	  "citron",
	  "vanilla bean",
	  "chilli flake",
	  "passion fruit",
	  "couscous",
	  "curry paste",
	  "grapefruit",
	  "blueberry",
	  "pineapples",
	  "acorn squash",
	  "poppy seed",
	  "Goji berry",
	  "endive",
	  "lentil",
	  "orange",
	  "powdered sugar",
	  "lime",
	  "berry",
	  "pomelo",
	  "cayenne pepper",
	  "elderberry",
	  "cider",
	  "nectarine",
	  "canola oil",
	  "nutmeg",
	  "onion powder",
	  "pinto beans",
	  "pumpkin seed",
	  "pesto",
	  "peas",
	  "strawberry",
	  "acorn",
	  "pastry",
	  "pistachios",
	  "sorghum",
	  "black olive",
	  "rhubarb",
	  "coriander",
	  "shish",
	  "red pepper flake",
	  "Tabasco sauce",
	  "plum tomato",
	  "coconut yogurt",
	  "tomato juice",
	  "cashew nut",
	  "leek",
	  "hot sauce",
	  "tomato sauce",
	  "nosh",
	  "turmeric",
	  "fennel",
	  "jam",
	  "sugar",
	  "toast",
	  "five-spice powder",
	  "pilaf",
	  "pancake",
	  "pine nuts",
	  "sea cucumber",
	  "truffle",
	  "almond extract",
	  "coconut milk",
	  "watercress",
	  "melon",
	  "muffin",
	  "persimmon",
	  "basil",
	  "lettuce",
	  "coleslaw",
	  "cantaloupe",
	  "flour",
	  "lemon grass",
	  "soy sauce",
	  "pecans",
	  "mango",
	  "coconut milk",
	  "bran",
	  "cherry",
	  "bruschetta",
	  "walnut",
	  "raspberry",
	  "mustard",
	  "apple cider vinegar",
	  "date sugar",
	  "pickle",
	  "spaghetti",
	  "wine",
	  "dill",
	  "flax seed",
	  "marmalade",
	  "rice vinegar",
	  "crouton",
	  "potato",
	  "kohlrabi",
	  "marshmallow",
	  "cannellini beans",
	  "spinach",
	  "paprika",
	  "tapioca",
	  "chutney",
	  "peapod",
	  "lychee",
	  "bouillon",
	  "yam",
	  "sweet pepper",
	  "oil",
	  "black bean",
	  "cashew",
	  "cucumber",
	  "yeast",
	  "barbecue sauce",
	  "cranberry",
	  "garlic",
	  "guava",
	  "tarragon",
	  "avocado",
	  "olive oil",
	  "ketchup",
	  "corn",
	  "almond paste",
	  "macaroni",
	  "sherry",
	  "turnip",
	  "lemon zest",
	  "chipotle pepper"
	]
  }
  `)
